// Settings for the full-server systems (merged into SETTING_KEYS).
export const EXTRA_SETTING_KEYS = {
  staff_roles:           { type: "rolelist", group: "Core",       desc: "Extra roles that count as staff (besides staff_role and above)" },
  leadership_roles:      { type: "rolelist", group: "Core",       desc: "Leadership roles (pinged for anti-nuke, can review everything)" },
  invite_role_code:      { type: "text",    group: "Welcome",     desc: "Invite code that grants invite_role to people who join through it" },
  invite_role:           { type: "role",    group: "Welcome",     desc: "Role given to people who joined via invite_role_code" },
  captcha_below_days:    { type: "number",  group: "Verify",      desc: "Only accounts younger than this get the captcha (0 = use verify_mode for everyone)" },
  verify_young_action:   { type: "text",    group: "Verify",      desc: "Accounts under min_account_age_days: wait (told when) | review (staff Approve/Kick queue)" },
  verify_review_channel: { type: "channel", group: "Verify",      fallback: "reports-queue, staff-alerts", desc: "Where new-account reviews go (review mode)" },
  welcome_on:            { type: "text",    group: "Welcome",     desc: "join (default) | verify — when to post the welcome card" },
  welcome_dm:            { type: "text",    group: "Welcome",     desc: "DM sent after verifying ({user}, {server}); channel mentions allowed" },
  welcome_card_subtitle: { type: "text",    group: "Welcome",     desc: "Card subtitle ({count}, {server}), default 'Member #{count} of {server}'" },
  ticket_staff_roles:    { type: "rolelist", group: "Tickets",    desc: "Roles that see every ticket" },
  ticket_ban_role:       { type: "role",    group: "Tickets",     fallback: "ticket banned", desc: "Members with this role can't open tickets" },
  ticket_close_delay:    { type: "number",  group: "Tickets",     desc: "Seconds before a closed ticket is deleted (default 10)" },
  ticket_claim_reminder_hours: { type: "number", group: "Tickets", desc: "Ping the claimer if no staff reply for this long (default 24)" },
  xp_min:                { type: "number",  group: "Levels",      desc: "Min XP per message (default 15)" },
  xp_max:                { type: "number",  group: "Levels",      desc: "Max XP per message (default 25)" },
  xp_cooldown_seconds:   { type: "number",  group: "Levels",      desc: "Seconds between XP-earning messages (default 60)" },
  voice_xp:              { type: "number",  group: "Levels",      desc: "XP per 5 min in voice with 2+ non-AFK people (0 = off)" },
  xp_booster_multiplier: { type: "number",  group: "Levels",      desc: "XP multiplier for server boosters (default 1)" },
  rank_up_message:       { type: "text",    group: "Levels",      desc: "Rank-up text ({user}, {rank}, {level}); default '{user} is now a {rank}.'" },
  leaderboard_mode:      { type: "text",    group: "Levels",      desc: "!leaderboard shows: xp | economy (default economy)" },
  xp_admin_roles:        { type: "rolelist", group: "Levels",     desc: "Who can use !xp add/remove/reset (default staff)" },
  starboard_source_channels: { type: "list", group: "Community",  desc: "Only these channels feed the starboard (empty = all)" },
  giveaway_channel:      { type: "channel", group: "Community",   fallback: "giveaways", desc: "Where !giveaway prize posts" },
  giveaway_ping_role:    { type: "role",    group: "Community",   fallback: "giveaway ping", desc: "Pinged for new giveaways" },
  giveaway_host_roles:   { type: "rolelist", group: "Community",  desc: "Who can host prize giveaways (default staff)" },
  suggestion_ban_role:   { type: "role",    group: "Community",   fallback: "suggestion banned", desc: "Can't post suggestions" },
  accepted_channel:      { type: "channel", group: "Community",   fallback: "accepted-ideas", desc: "Accepted suggestions are copied here" },
  poll_channel:          { type: "channel", group: "Community",   fallback: "polls", desc: "Where staff polls go" },
  poll_ping_role:        { type: "role",    group: "Community",   fallback: "poll ping", desc: "Pinged for polls" },
  poll_staff_only:       { type: "toggle",  group: "Community",   desc: "Only staff can create polls" },
  sotw_winner_role:      { type: "role",    group: "Community",   fallback: "contest winner", desc: "Screenshot of the Week winner gets this for 7 days" },
  hall_of_fame_channel:  { type: "channel", group: "Community",   fallback: "hall-of-fame", desc: "SOTW winners are posted here" },
  birthday_hour:         { type: "number",  group: "Community",   desc: "UTC hour for birthday posts (default 12)" },
  raid_young_threshold:  { type: "number",  group: "Safety",      desc: "Young (<24h) accounts joining within raid_young_window_seconds that trigger raid mode (default 5)" },
  raid_young_window_seconds: { type: "number", group: "Safety",   desc: "Window for the young-account trigger (default 60)" },
  raid_set_verification: { type: "toggle",  group: "Safety",      desc: "Raise server verification to Highest during raid mode (default on)" },
  raid_slowmode_categories: { type: "list", group: "Safety",      desc: "Categories slowed during raid mode (empty = every text channel)" },
  raid_alert_channels:   { type: "list",    group: "Safety",      desc: "Where raid alerts go (default staff alert channel)" },
  raid_alert_roles:      { type: "rolelist", group: "Safety",     desc: "Roles pinged on raid (default staff role)" },
  raid_command_role:     { type: "role",    group: "Safety",      desc: "Minimum role for !raidmode (default staff)" },
  raid_timeout_young:    { type: "toggle",  group: "Safety",      desc: "Time out (1h) <7-day accounts that joined during the trigger (default on)" },
  antinuke_role_threshold: { type: "number", group: "Safety",     desc: "Role creates/deletes per minute that trigger anti-nuke (default 3)" },
  antinuke_webhook_threshold: { type: "number", group: "Safety",  desc: "Webhooks created per minute that trigger anti-nuke (default 3)" },
  antinuke_alert_channel:{ type: "channel", group: "Safety",      fallback: "admin-chat", desc: "Anti-nuke reports" },
  antinuke_restore:      { type: "toggle",  group: "Safety",      desc: "Recreate deleted channels/roles from the last snapshot (default on)" },
  scam_timeout_minutes:  { type: "number",  group: "Safety",      desc: "Timeout for scam links (default 1440 = 1 day)" },
  qr_min_account_days:   { type: "number",  group: "Safety",      desc: "QR images are blocked for accounts younger than this (default 30)" },
  qr_trusted_role:       { type: "role",    group: "Safety",      desc: "Members at/above this role may post QR images" },
  scam_link_raid_accounts: { type: "number", group: "Safety",     desc: "Same link from this many accounts in 5 min starts raid mode (default 3)" },
  warn_ban_confirm:      { type: "toggle",  group: "Safety",      desc: "Ban at the final strike needs an Admin+ confirm button (default off)" },
  warn_ban_confirm_role: { type: "role",    group: "Safety",      desc: "Minimum role that can confirm a strike ban" },
  unwarn_role:           { type: "role",    group: "Safety",      desc: "Minimum role for !unwarn (default staff)" },
  spam_filter_categories:{ type: "list",    group: "Safety",      desc: "Categories where spam filters apply (adds to spam_filter_channels)" },
  spam_rate_limit:       { type: "text",    group: "Safety",      desc: "'5/5' = 5 messages in 5 s → delete + 5 min timeout (empty = off)" },
  spam_duplicate_limit:  { type: "text",    group: "Safety",      desc: "'3/30' = same message 3× in 30 s → delete + timeout (empty = off)" },
  spam_exempt_roles:     { type: "rolelist", group: "Safety",     desc: "Exempt from caps/emoji filter" },
  mention_spam_strike:   { type: "toggle",  group: "Safety",      desc: "Mention spam also adds a warning strike" },
  bot_command_exceptions:{ type: "text",    group: "Clean",       desc: "Allowed outside bot-commands, e.g. 'rank:rank-ups,link:verify'" },
  wrong_channel_delay:   { type: "number",  group: "Clean",       desc: "Seconds before deleting a wrong-channel command (default 3)" },
  autothread_name_length:{ type: "number",  group: "Clean",       desc: "Auto-thread name length (default 40)" },
  media_link_domains:    { type: "text",    group: "Clean",       desc: "Links allowed in media-only channels (default youtube,youtu.be,tiktok,medal,streamable,imgur,roblox)" },
  bug_forums:            { type: "list",    group: "Clean",       fallback: "bug-reports, test-bugs", desc: "Bug forums (Confirm button, Fixed/Can't Reproduce lock after 7d)" },
  duplicate_forums:      { type: "list",    group: "Clean",       fallback: "suggestions, bug-reports, test-bugs", desc: "Forums that get the duplicate check" },
  forum_inactive_days:   { type: "number",  group: "Clean",       desc: "Archive any managed forum post idle this long (default 30)" },
  suggestion_denied_archive_days: { type: "number", group: "Clean", desc: "Denied suggestions archive after (default 3; locked immediately)" },
  suggestion_accepted_lock_days: { type: "number", group: "Clean", desc: "Accepted suggestions lock after (default 14)" },
  status_category:       { type: "text",    group: "Roblox",      desc: "Category name/ID to put the player-count channel in" },
  roblox_update_announce:{ type: "toggle",  group: "Roblox",      desc: "Post in updates channel when the game's last-updated time changes (default on)" },
  patch_notes_channel:   { type: "channel", group: "Roblox",      fallback: "patch-notes", desc: "Full patch notes" },
  announcements_channel: { type: "channel", group: "Roblox",      fallback: "announcements", desc: "Short cross-post of patch notes" },
  patch_roles:           { type: "rolelist", group: "Roblox",     desc: "Who can use !patchnotes (default staff)" },
  link_set_nickname:     { type: "toggle",  group: "Roblox",      desc: "Set nickname to Roblox display name after linking (default off)" },
  link_phrase_words:     { type: "number",  group: "Roblox",      desc: "Words in the link phrase (default 6)" },
  leaderboard_endpoint:  { type: "text",    group: "Roblox",      desc: "HTTPS URL returning leaderboard JSON (see README)" },
  records_channel:       { type: "channel", group: "Roblox",      fallback: "records-showcase", desc: "New #1 records are announced here" },
  playtest_host_roles:   { type: "rolelist", group: "Roblox",     desc: "Who can schedule playtests (default staff)" },
  playtest_ping_role:    { type: "role",    group: "Roblox",      fallback: "playtest ping", desc: "Testers with this role get the 30-min ping" },
  test_builds_channel:   { type: "channel", group: "Roblox",      fallback: "test-builds", desc: "Join instructions are posted here 30 min before" },
  playtest_join_text:    { type: "text",    group: "Roblox",      desc: "Join instructions text" },
  playtest_feedback_channels: { type: "list", group: "Roblox",    fallback: "test-feedback, test-bugs, perf-reports", desc: "Linked in the post-playtest reminder" },
  bug_confirm_roles:     { type: "rolelist", group: "Roblox",     desc: "Who can press Confirm on bug posts (default staff)" },
  bug_hunter_role:       { type: "role",    group: "Roblox",      fallback: "bug hunter", desc: "Given after bug_hunter_threshold confirmed bugs" },
  bug_hunter_threshold:  { type: "number",  group: "Roblox",      desc: "Confirmed bugs needed for Bug Hunter (default 3)" },
  current_version:       { type: "text",    group: "Roblox",      desc: "Game version used in 'fixed in <version>' DMs" },
  counter_category:      { type: "text",    group: "Roblox",      desc: "Category name/ID for counter channels" },
  weekly_report:         { type: "toggle",  group: "Roblox",      desc: "Weekly staff report (default on)" },
};
